# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nanograd',
                'doc_host': 'https://vempaliakhil96.github.io',
                'git_url': 'https://github.com/vempaliakhil96/nanograd',
                'lib_path': 'nanograd'},
  'syms': {'nanograd.core': {'nanograd.core.foo': ('core.html#foo', 'nanograd/core.py')}}}
