# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nanograd',
                'doc_host': 'https://vempaliakhil96.github.io',
                'git_url': 'https://github.com/vempaliakhil96/nanograd',
                'lib_path': 'nanograd'},
  'syms': { 'nanograd.core': { 'nanograd.core.Value': ('value.html#value', 'nanograd/core.py'),
                               'nanograd.core.Value.__add__': ('value.html#value.__add__', 'nanograd/core.py'),
                               'nanograd.core.Value.__init__': ('value.html#value.__init__', 'nanograd/core.py'),
                               'nanograd.core.Value.__mul__': ('value.html#value.__mul__', 'nanograd/core.py'),
                               'nanograd.core.Value.__repr__': ('value.html#value.__repr__', 'nanograd/core.py')}}}
