# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_value.ipynb.

# %% auto 0
__all__ = ['Value']

# %% ../nbs/01_value.ipynb 1
class Value:
    def __init__(self, data):
        self.data = data

    def __repr__(self):
        return f"Value(data={self.data})"

    def __add__(self, other):
        return Value(self.data + other.data)
